aggregate() or agg(): The core method that applies one or more functions to the data.<br>
groupby(): Used to group data based on one or more columns before applying an aggregation function to each group

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('student_performance.csv')
print(df.head())

  Student_ID  Age  Gender  Class  Attendance_Percentage  Math_Score  \
0      S0001   15    Male     12                   65.0         NaN
1      S0002   19  Female      9                   58.0        80.0
2      S0003   14  Female     12                    NaN        83.0
3      S0004   18  Female      9                   68.0        68.0
4      S0005   14    Male     10                   80.0        41.0

   Science_Score  English_Score  Final_Percentage
0            NaN           72.0             50.33
1           44.0           35.0             53.00
2           73.0           59.0             71.67
3            NaN           77.0             64.33
4            NaN           36.0             41.00

# agg()

In [3]:
# to calculate the mean of the specific column we can use agg() method and pass the function name as a string to it
# here the function is mean
df['Math_Score'].agg('mean')

np.float64(68.73076923076923)

In [4]:
# to calculate the median of the specific column we can use agg() method and pass the function name as a string to it
# here the function is median
df['Science_Score'].agg('median')

np.float64(71.0)

In [5]:
# to calculate the minimum value of the specific column we can use agg() method and pass the function name as a string to it
# here the function is min
df['Science_Score'].agg('min')

np.float64(35.0)

In [6]:
# to calculate the maximum value of the specific column we can use agg() method and pass the function name as a string to it
# here the function is max
df['Science_Score'].agg('max')

np.float64(100.0)

In [7]:
# to calculate the standard deviation of the specific column we can use agg() method and pass the function name as a string to it
# here the function is std
df['Science_Score'].agg('std')

np.float64(19.448627453201343)

In [8]:
# to claculate number of non null vlaues in the specific column we can use agg() method and pass the function name as a string to it
# here the function is count

df['Science_Score'].agg('count')

np.int64(119)

In [9]:
# to calculate the variance of the specific column we can use agg() method and pass the function name as a string to it
# here the function is var
df['Science_Score'].agg('var')

np.float64(378.2491098134169)

In [10]:
# to calculate the sum of the specific column we can use agg() method and pass the function name as a string to it
# here the function is sum
df['Math_Score'].agg('sum')

np.float64(8935.0)

In [11]:
# here we can pass multiple functions to the agg() method by passing a list of function names as strings to it
df['Math_Score'].agg(['mean','max','min','std','var','count'])

mean      68.730769
max      100.000000
min       35.000000
std       18.450768
var      340.430829
count    130.000000
Name: Math_Score, dtype: float64

In [12]:
# to calculate the aggregate function on multiple columns we can pass a list of column names to the agg() method and then pass the function name as a string to it
df[['Math_Score', 'Science_Score']].agg("sum", axis=1)
# here we are using axis = 1 to calculate sum across the columns for each row

0        0.0
1      124.0
2      156.0
3       68.0
4       41.0
       ...
143      0.0
144     83.0
145     99.0
146    152.0
147    116.0
Length: 148, dtype: float64

In [13]:
#  if we use axis = 0 then it will calculate the sum for each column separately
df[['Math_Score', 'Science_Score']].agg("sum", axis=0)

Math_Score       8935.0
Science_Score    8005.0
dtype: float64

In [14]:
# here we are performing column wise aggregation with multiple functions on multiple columns here default axis = 0
df.agg({'Math_Score' : ['sum', 'mean'], 'Science_Score' : ['sum', 'max']})
# here if you observe the output mean for Science_Score is NaN because we have not specified the function for that column so it will return NaN for that column and for Math_Score we have specified both sum and mean so it will return the sum and mean for that column
# NaN here means “function not applied”, not bad data

       Math_Score  Science_Score
sum   8935.000000         8005.0
mean    68.730769            NaN
max           NaN          100.0

# Groupby
what groupby does
First, it splits the data into groups.
Second, it applies an aggregation on each group.
Finally, it combines the results into a new table.


split-->Apply-->combine

In [15]:
import pandas as pd

df = pd.DataFrame({
    "gender": ["male", "female", "female", "male", "female"],
    "lunch": ["standard", "free", "standard", "free", "standard"],
    "math_score": [72, 85, 90, 60, 78],
    "reading_score": [70, 88, 92, 65, 80]
})
print(df)

   gender     lunch  math_score  reading_score
0    male  standard          72             70
1  female      free          85             88
2  female  standard          90             92
3    male      free          60             65
4  female  standard          78             80

In [16]:
# here we are splitting data into groups by using gender column, appling aggregations on math_score column for each group and last we are combining the results into one group
df.groupby("gender")["math_score"].mean()
# here pandas looks at gender column, finds the unique values in the coluymns and splits them into two groups one is male and anoother is female

gender
female    84.333333
male      66.000000
Name: math_score, dtype: float64

In [17]:
# here we are splitting the data into groups using gender column, we are appling aggregation on mathscore and reading score for each group and we last we are the results into one group
df.groupby("gender")[["math_score", "reading_score"]].mean()

        math_score  reading_score
gender
female   84.333333      86.666667
male     66.000000      67.500000

In [18]:
# multiple aggregations on multiple columns
df.groupby("gender").agg({
    "math_score": ["mean", "max"],
    "reading_score": "min"
})

       math_score     reading_score
             mean max           min
gender
female  84.333333  90            80
male    66.000000  72            65

In [19]:
# here we are splitting data into groups using two columns one is lunch and another is gender and then we are applying aggregation on math_score column for each group and last we are combining the results into one group
df.groupby(["gender", "lunch"])["math_score"].mean()

# interview answering style

# We group data by gender and lunch type, compute the mean math score for each combination, and return a multi-level indexed summary table.”

gender  lunch
female  free        85.0
        standard    84.0
male    free        60.0
        standard    72.0
Name: math_score, dtype: float64

In [20]:
# we can also calculate the size of each group by using size() method
df.groupby("gender").size()

gender
female    3
male      2
dtype: int64

In [21]:
# we can also add the the group results to the original dataframe by using transform() method
df["avg_math_by_gender"] = df.groupby("gender")["math_score"].transform("mean")
print(df)
#

   gender     lunch  math_score  reading_score  avg_math_by_gender
0    male  standard          72             70           66.000000
1  female      free          85             88           84.333333
2  female  standard          90             92           84.333333
3    male      free          60             65           66.000000
4  female  standard          78             80           84.333333

In [22]:
# we can also sort the group results by using sort_values() method
df.groupby("gender")["math_score"].mean().sort_values(ascending=True)
df
# we are using ascending = False to sort the values in descending order if we want to sort in ascending order then we can use ascending = True or we can simply omit the ascending parameter because by default it is True

   gender     lunch  math_score  reading_score  avg_math_by_gender
0    male  standard          72             70           66.000000
1  female      free          85             88           84.333333
2  female  standard          90             92           84.333333
3    male      free          60             65           66.000000
4  female  standard          78             80           84.333333

lets work with stufdent performance data

In [23]:
df = pd.read_csv('student_performance.csv')
print(df.head())

  Student_ID  Age  Gender  Class  Attendance_Percentage  Math_Score  \
0      S0001   15    Male     12                   65.0         NaN
1      S0002   19  Female      9                   58.0        80.0
2      S0003   14  Female     12                    NaN        83.0
3      S0004   18  Female      9                   68.0        68.0
4      S0005   14    Male     10                   80.0        41.0

   Science_Score  English_Score  Final_Percentage
0            NaN           72.0             50.33
1           44.0           35.0             53.00
2           73.0           59.0             71.67
3            NaN           77.0             64.33
4            NaN           36.0             41.00

In [24]:
df.groupby('Age')['Math_Score'].mean()

Age
14    63.000000
15    78.937500
16    72.000000
17    65.136364
18    70.238095
19    69.000000
Name: Math_Score, dtype: float64

In [25]:
df.groupby("Gender")[["Math_Score", "Science_Score"]].mean()

        Math_Score  Science_Score
Gender
Female   71.714286      66.342466
Male     64.396226      68.739130

In [26]:
df.groupby("Gender").agg({
    "Math_Score": ["mean", "max"],
    "English_Score": ["min","mean"]
})

       Math_Score        English_Score
             mean    max           min       mean
Gender
Female  71.714286  100.0          35.0  70.129870
Male    64.396226  100.0          35.0  70.890909

In [27]:
df.groupby(["Gender", "Age"])["Math_Score"].mean()

Gender  Age
Female  14     63.384615
        15     79.636364
        16     78.875000
        17     71.230769
        18     72.857143
        19     69.166667
Male    14     62.687500
        15     77.400000
        16     61.000000
        17     56.333333
        18     65.000000
        19     68.727273
Name: Math_Score, dtype: float64

In [28]:
df["avg_math_by_age"] = df.groupby("Age")["Math_Score"].transform("mean").round(2)
# you can also use round() method to round values to specific number of decimal places here we are rounding to 2 decimal places
print(df)
#

    Student_ID  Age  Gender  Class  Attendance_Percentage  Math_Score  \
0        S0001   15    Male     12                   65.0         NaN
1        S0002   19  Female      9                   58.0        80.0
2        S0003   14  Female     12                    NaN        83.0
3        S0004   18  Female      9                   68.0        68.0
4        S0005   14    Male     10                   80.0        41.0
..         ...  ...     ...    ...                    ...         ...
143      S0144   14    Male     11                   94.0         NaN
144      S0145   19    Male     12                   56.0        83.0
145      S0146   19  Female     12                    NaN        51.0
146      S0147   19    Male     11                   54.0        96.0
147      S0148   19  Female     11                   91.0        65.0

     Science_Score  English_Score  Final_Percentage  avg_math_by_age
0              NaN           72.0             50.33            78.94
1             44.0           35.0             53.00            69.00
2             73.0           59.0             71.67            63.00
3              NaN           77.0             64.33            70.24
4              NaN           36.0             41.00            63.00
..             ...            ...               ...              ...
143            NaN           82.0             64.33            63.00
144            NaN           97.0             93.00            69.00
145           48.0           44.0             47.67            69.00
146           56.0           50.0             67.33            69.00
147           51.0           65.0             60.33            69.00

[148 rows x 10 columns]

In [29]:
df.groupby("Gender")["Math_Score"].mean().sort_values(ascending=False)
print(df)

    Student_ID  Age  Gender  Class  Attendance_Percentage  Math_Score  \
0        S0001   15    Male     12                   65.0         NaN
1        S0002   19  Female      9                   58.0        80.0
2        S0003   14  Female     12                    NaN        83.0
3        S0004   18  Female      9                   68.0        68.0
4        S0005   14    Male     10                   80.0        41.0
..         ...  ...     ...    ...                    ...         ...
143      S0144   14    Male     11                   94.0         NaN
144      S0145   19    Male     12                   56.0        83.0
145      S0146   19  Female     12                    NaN        51.0
146      S0147   19    Male     11                   54.0        96.0
147      S0148   19  Female     11                   91.0        65.0

     Science_Score  English_Score  Final_Percentage  avg_math_by_age
0              NaN           72.0             50.33            78.94
1             44.0           35.0             53.00            69.00
2             73.0           59.0             71.67            63.00
3              NaN           77.0             64.33            70.24
4              NaN           36.0             41.00            63.00
..             ...            ...               ...              ...
143            NaN           82.0             64.33            63.00
144            NaN           97.0             93.00            69.00
145           48.0           44.0             47.67            69.00
146           56.0           50.0             67.33            69.00
147           51.0           65.0             60.33            69.00

[148 rows x 10 columns]

# TASK
HERE IS ANOTHER DATA FILE (laptop_prices.csv) DO THE SAME EXAMPLES BELOW WHICH I HAVE DONE ABOVE FOR BETTER PRACTICE

In [30]:
import pandas as pd
df = pd.read_csv('laptop_prices.csv')
print(df.head())

   laptop_ID Company      Product   TypeName  Inches  \
0          1   Apple  MacBook Pro  Ultrabook    13.3
1          2   Apple  Macbook Air  Ultrabook    13.3
2          3      HP       250 G6   Notebook    15.6
3          4   Apple  MacBook Pro  Ultrabook    15.4
4          5   Apple  MacBook Pro  Ultrabook    13.3

                     ScreenResolution                         Cpu   Ram  \
0  IPS Panel Retina Display 2560x1600        Intel Core i5 2.3GHz   8GB
1                            1440x900        Intel Core i5 1.8GHz   8GB
2                   Full HD 1920x1080  Intel Core i5 7200U 2.5GHz   8GB
3  IPS Panel Retina Display 2880x1800        Intel Core i7 2.7GHz  16GB
4  IPS Panel Retina Display 2560x1600        Intel Core i5 3.1GHz   8GB

                Memory                           Gpu  OpSys  Weight  \
0            128GB SSD  Intel Iris Plus Graphics 640  macOS  1.37kg
1  128GB Flash Storage        Intel HD Graphics 6000  macOS  1.34kg
2            256GB SSD         Intel HD Graphics 620  No OS  1.86kg
3            512GB SSD            AMD Radeon Pro 455  macOS  1.83kg
4            256GB SSD  Intel Iris Plus Graphics 650  macOS  1.37kg

   Price_euros
0      1339.69
1       898.94
2       575.00
3      2537.45
4      1803.60