In [1]:
import pandas as pd

# concat()

concatenation:<br>
The operation of joining two or more character strings, values, or data sets end-to-end to create a single, longer string or sequence

In [2]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                    'age': [30, 23, 25, 22]})
df2 = pd.DataFrame({'id': ['E', 'F', 'G', 'F'],
                    'age': [40, 21, 19, 24]})

In [3]:
# tho concatenate the two dataframes we can use concat() method of pandas library 
pd.concat([df1, df2])

  id  age
0  A   30
1  B   23
2  C   25
3  D   22
0  E   40
1  F   21
2  G   19
3  F   24

In [4]:
# if you see the aboves example output you will see that the index is repeated because we are concatenating along rows and by default the index is not reseted so to reset the index we can use ignore_index parameter and set it to True
pd.concat([df1, df2], ignore_index=True)

  id  age
0  A   30
1  B   23
2  C   25
3  D   22
4  E   40
5  F   21
6  G   19
7  F   24

In [5]:
# we can specify the axis parameter to concatenate along rows or columns
# to concatenate along rows we have to use axis = 0 
# by default the aixs is 0
pd.concat([df1, df2], axis=0, ignore_index=True)

  id  age
0  A   30
1  B   23
2  C   25
3  D   22
4  E   40
5  F   21
6  G   19
7  F   24

In [6]:
# to concatenate along columns we have to use axis = 1
pd.concat([df1, df2], axis=1)

  id  age id  age
0  A   30  E   40
1  B   23  F   21
2  C   25  G   19
3  D   22  F   24

# merge()

merge means <br>
to combine or join

In [7]:
import pandas as pd

customers = pd.DataFrame({
    "customer_id": [1, 2, 3],
    "name": ["A", "B", "C"]
})

orders = pd.DataFrame({
    "customer_id": [1, 1, 2],
    "order_amount": [250, 300, 150]
})

In [8]:
# here we are merging the two dataframes on the common column 'customer_id' and by default it will perform an inner join which means it will only keep the rows that have matching keys in both dataframes
# here if we observe the two dataframes we have one common column which is 'customer_id'
# to merge by using the common column we can use on parameter and the name of the common column

pd.merge(customers, orders, on='customer_id')

   customer_id name  order_amount
0            1    A           250
1            1    A           300
2            2    B           150

In [9]:
# This is the default merge method in pandas. It acts like an intersection in set theory, keeping only the records that have a match in both the left and right datasets. 

pd.merge(customers, orders, on='customer_id', how='inner')  # inner join

   customer_id name  order_amount
0            1    A           250
1            1    A           300
2            2    B           150

In [10]:
# This is a full outer join. It combines the data, keeping every single row from both DataFrames. If a row from one DataFrame doesn't have a matching key in the other, it fills in NaN
pd.merge(customers,orders,on = 'customer_id', how='outer')

   customer_id name  order_amount
0            1    A         250.0
1            1    A         300.0
2            2    B         150.0
3            3    C           NaN

In [11]:
# when we are combining two datasets, to keep all rows from the left table and only matching rows from the right table
# if there is no match in the right table then the result will have NaN values for the columns of the right table
pd.merge(customers, orders, on='customer_id', how='left')

   customer_id name  order_amount
0            1    A         250.0
1            1    A         300.0
2            2    B         150.0
3            3    C           NaN

In [12]:
# when we are combining two datasets, to keep all rows from the right table and only matching rows from the left table
# if there is no match in the left table then the result will have NaN values for the columns of the left table
pd.merge(customers, orders, on="customer_id", how="right")
# A RIGHT merge shows NaN only when the right table has keys missing in the left table

   customer_id name  order_amount
0            1    A           250
1            1    A           300
2            2    B           150