In [35]:
import pandas as pd
import numpy as np

In [36]:
df = pd.read_csv('student_performance.csv')
df.head()

,Student_ID,Age,Gender,Class,Attendance_Percentage,Math_Score,Science_Score,English_Score,Final_Percentage
0,S0001,15,Male,12,65.0,NaN,NaN,72.0,50.33
1,S0002,19,Female,9,58.0,80.0,44.0,35.0,53.00
2,S0003,14,Female,12,NaN,83.0,73.0,59.0,71.67
3,S0004,18,Female,9,68.0,68.0,NaN,77.0,64.33
4,S0005,14,Male,10,80.0,41.0,NaN,36.0,41.00

In [37]:
# here we are checking the data type of student id column
df['Student_ID'].dtypes

In [38]:
# as the dtype of gender column is string, if you have observed the Gender column it has smaller case values
# so we are converting them uppercase using str.upper() method
df['Gender'].str.upper()

0        MALE
1      FEMALE
2      FEMALE
3      FEMALE
4        MALE
        ...
143      MALE
144      MALE
145    FEMALE
146      MALE
147    FEMALE
Name: Gender, Length: 148, dtype: str

In [39]:
# herewe are converting them to lowercase using str.lower() method
df['Gender'].str.lower()

0        male
1      female
2      female
3      female
4        male
        ...
143      male
144      male
145    female
146      male
147    female
Name: Gender, Length: 148, dtype: str

In [40]:
# strip the prefix
# her we are replacing the 'S' in the student_id column with A
df['Student_ID'].str.replace('S', 'A')

0      A0001
1      A0002
2      A0003
3      A0004
4      A0005
       ...
143    A0144
144    A0145
145    A0146
146    A0147
147    A0148
Name: Student_ID, Length: 148, dtype: str

In [41]:
# boolean mask, like isin() but for substrings

# here we are checking if the string '1' is present in the Student_ID column
df['Student_ID'].str.contains('1')

0       True
1      False
2      False
3      False
4      False
       ...
143     True
144     True
145     True
146     True
147     True
Name: Student_ID, Length: 148, dtype: bool

In [42]:
data = {'Name': ['Peter Parker', 'Baby Johnson', 'Santoor Mummy'],
       'Age': [25, 30, 35],
       'City': ['New York', 'London', 'Paris']}
df = pd.DataFrame(data)
df

            Name  Age      City
0   Peter Parker   25  New York
1   Baby Johnson   30    London
2  Santoor Mummy   35     Paris

In [43]:
# here we are splitting the Name column into two columns, First Name and Last Name
# as our previous dataset studentperformance.csv does not have a name column, we are creating a new dataset with name column
df['Name'].str.split(' ', expand=True)

         0        1
0    Peter   Parker
1     Baby  Johnson
2  Santoor    Mummy

In [44]:
# here we are removing the white space from the Name column using str.strip() method
# as our our Name column does not have any white space, you are not seeing any changes in the output, but if you have a white space in the Name column, it will be removed

df['Name'].str.strip()    # remove whitespace

0     Peter Parker
1     Baby Johnson
2    Santoor Mummy
Name: Name, dtype: str

In [45]:
# here we are checking the length of the string in the Name column
df['Name'].str.len()

0    12
1    12
2    13
Name: Name, dtype: int64