# Date Handling

In [109]:
import pandas as pd
import numpy as np

In [110]:
df = pd.read_csv('countryLockdowndates.csv')
df.head(5)

,Country/Region,Date,Type,Reference
0,Mainland China,2020-01-23,Full,https://en.wikipedia.org/wiki/2019%E2%80%9320_...
1,Hong Kong,2020-03-23,Full,https://en.wikipedia.org/wiki/2020_coronavirus...
2,Macau,2020-01-26,Full,https://en.wikipedia.org/wiki/2020_coronavirus...
3,Taiwan,2020-02-02,Full,https://en.wikipedia.org/wiki/2020_coronavirus...
4,US,2020-03-23,Partial,https://en.wikipedia.org/wiki/2020_coronavirus...

In [111]:
# these are the columsn which we have in our dataset
df.columns.tolist()

['Country/Region', 'Date', 'Type', 'Reference']

In [112]:
# checking the data type of the Date column
df['Date'].dtype

In [113]:
# as in the previous step we saw that the datatype of Date column is string, 
# so we need to convert it to datetime format so that we can perform date operations on it.
df['Date'] = pd.to_datetime(df['Date'])   # convert string column to real datetime

In [114]:
# here we are extracting Year from Date column and creating a new column called Year in our dataframe
df['Year'] = df['Date'].dt.year
df.head()

,Country/Region,Date,Type,Reference,Year
0,Mainland China,2020-01-23,Full,https://en.wikipedia.org/wiki/2019%E2%80%9320_...,2020.0
1,Hong Kong,2020-03-23,Full,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0
2,Macau,2020-01-26,Full,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0
3,Taiwan,2020-02-02,Full,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0
4,US,2020-03-23,Partial,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0

In [115]:
# here we are extracting month from Date column and creating a new column called Month in our dataframe
df['Month'] = df['Date'].dt.month
df.head()

,Country/Region,Date,Type,Reference,Year,Month
0,Mainland China,2020-01-23,Full,https://en.wikipedia.org/wiki/2019%E2%80%9320_...,2020.0,1.0
1,Hong Kong,2020-03-23,Full,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0,3.0
2,Macau,2020-01-26,Full,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0,1.0
3,Taiwan,2020-02-02,Full,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0,2.0
4,US,2020-03-23,Partial,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0,3.0

In [116]:
# here we are finding the name of the day by using date column
# for that we will be using .dt.day_name() function which will return the weekday name for that date.
df['Weekday'] = df['Date'].dt.day_name()
df.head()

,Country/Region,Date,Type,Reference,Year,Month,Weekday
0,Mainland China,2020-01-23,Full,https://en.wikipedia.org/wiki/2019%E2%80%9320_...,2020.0,1.0,Thursday
1,Hong Kong,2020-03-23,Full,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0,3.0,Monday
2,Macau,2020-01-26,Full,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0,1.0,Sunday
3,Taiwan,2020-02-02,Full,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0,2.0,Sunday
4,US,2020-03-23,Partial,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0,3.0,Monday

In [117]:
# here it give only the short name of the weekday like Mon, Tue, Wed, Thu, Fri, Sat, Sun
df['Weekday'] = df['Date'].dt.strftime('%a')

In [118]:
# as you have seen in our previous step, the weekday column is in string format, 
# so we will create a new column called Weekday_Num which will have the weekday number 
# for that we will be using .dt.dayofweek function which will return the weekday number for that date.
"""
where Monday = 0, Tuesday = 1, Wednesday = 2, Thursday = 3, Friday = 4, Saturday = 5, Sunday = 6
"""
df['Weekday_Num'] = df['Date'].dt.dayofweek
df.head()

,Country/Region,Date,Type,Reference,Year,Month,Weekday,Weekday_Num
0,Mainland China,2020-01-23,Full,https://en.wikipedia.org/wiki/2019%E2%80%9320_...,2020.0,1.0,Thu,3.0
1,Hong Kong,2020-03-23,Full,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0,3.0,Mon,0.0
2,Macau,2020-01-26,Full,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0,1.0,Sun,6.0
3,Taiwan,2020-02-02,Full,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0,2.0,Sun,6.0
4,US,2020-03-23,Partial,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0,3.0,Mon,0.0

In [119]:
# here we are filtering the data by using date range
df[(df['Date'] >= '2020-01-01') & (df['Date'] <= '2020-06-30')]

,Country/Region,Date,Type,Reference,Year,Month,Weekday,Weekday_Num
0,Mainland China,2020-01-23,Full,https://en.wikipedia.org/wiki/2019%E2%80%9320_...,2020.0,1.0,Thu,3.0
1,Hong Kong,2020-03-23,Full,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0,3.0,Mon,0.0
2,Macau,2020-01-26,Full,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0,1.0,Sun,6.0
3,Taiwan,2020-02-02,Full,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0,2.0,Sun,6.0
4,US,2020-03-23,Partial,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0,3.0,Mon,0.0
...,...,...,...,...,...,...,...,...
168,Montenegro,2020-03-24,Full,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0,3.0,Tue,1.0
170,Kyrgyzstan,2020-03-24,Partial,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0,3.0,Tue,1.0
171,Mauritius,2020-03-17,Partial,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0,3.0,Tue,1.0
187,Uganda,2020-03-18,Full,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0,3.0,Wed,2.0
197,Mali,2020-03-18,Full,https://en.wikipedia.org/wiki/2020_coronavirus...,2020.0,3.0,Wed,2.0